spring.application.name=ticket-logger-v2-players

# DATABASE (Puerto que uses, 3306 o 3307)
spring.datasource.url=jdbc:mariadb://localhost:3307/players_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# 1. Fuerza a que se ejecute el data.sql aunque uses Hibernate
spring.sql.init.mode=always

# 2. (Opcional pero recomendado) Asegura que Hibernate no borre lo que data.sql inserte
spring.jpa.defer-datasource-initialization=true

# OAUTH2 GITHUB
spring.security.oauth2.client.registration.github.client-id=Ov23lil7DPZoh1WZ9T8B
spring.security.oauth2.client.registration.github.client-secret=68db1e933c9f25d68758cd07228073c664a9b9b5
spring.security.oauth2.client.registration.github.scope=user:email,read:user

server.port=8080