spring.application.name=ticket-logger-v2-players

# Database configuration
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# JPA - Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ESTA LÍNEA ES LA CLAVE:
# Hace que Spring espere a que Hibernate cree las tablas antes de ejecutar el data.sql
spring.jpa.defer-datasource-initialization=true

# Data Initialization
spring.sql.init.mode=always

# I18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8